config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'about#index'
  get 'home', to: 'home#index'
  get 'services', to: 'service#index'
  get 'contact-us', to: 'contact#index'
  get 'session', to: 'session#index'
  get 'verify-otp', to: 'session#verify_otp'
  resources :contact, only: [:index, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email" }
  validates :phone, presence: true, numericality: { only_integer: true }, length: { is: 10, message: "must be 10 digits" }
  validates :subject, presence: true
  validates :message, presence: true
  # validate :phone_number_format

  private

  def phone_number_format
    unless phone =~ /\A\+?\d{10,15}\z/
      errors.add(:phone, "must be a valid phone number (10-15 digits)")
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Your message has been sent successfully!"
      redirect_to contact_index_path
    else
      flash.now[:alert] = "There was an error sending your message. Please check the form and try again."
      render :index
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :subject, :project, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  layout false

  def index
  end

  def verify_otp
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/contact/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <body>
        <!-- Header Start -->
        <div class="container-fluid position-relative p-0">
            <div class="container-fluid bg-breadcrumb">
                <div class="container text-center py-5" style="max-width: 900px;">
                    <h4 class="text-white display-4 mb-4 wow fadeInDown" data-wow-delay="0.1s">Contact Us</h4>
                    <ol class="breadcrumb d-flex justify-content-center mb-0 wow fadeInDown" data-wow-delay="0.3s">
                        <li class="breadcrumb-item"> <%= link_to 'Home', home_path%></li>
                        <li class="breadcrumb-item"><a href="#">Pages</a></li>
                        <li class="breadcrumb-item active text-primary">About</li>
                    </ol>    
                </div>
            </div>
        </div>
        <!-- Header End -->
        
        <!-- Contact Start -->
        <div class="container-fluid contact py-5">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-xl-6">
                        <div class="wow fadeInUp" data-wow-delay="0.2s">
                            <div class="bg-light rounded p-5 mb-5">
                                <h4 class="text-primary mb-4">Get in Touch</h4>
                                <div class="row g-4">
                                    <div class="col-md-6">
                                        <div class="contact-add-item">
                                            <div class="contact-icon text-primary mb-4">
                                                <i class="fas fa-map-marker-alt fa-2x"></i>
                                            </div>
                                            <div>
                                                <h4>Address</h4>
                                                <p class="mb-0">123 Street New York.USA</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="contact-add-item">
                                            <div class="contact-icon text-primary mb-4">
                                                <i class="fas fa-envelope fa-2x"></i>
                                            </div>
                                            <div>
                                                <h4>Mail Us</h4>
                                                <p class="mb-0">info@example.com</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="contact-add-item">
                                            <div class="contact-icon text-primary mb-4">
                                                <i class="fa fa-phone-alt fa-2x"></i>
                                            </div>
                                            <div>
                                                <h4>Telephone</h4>
                                                <p class="mb-0">(+012) 3456 7890</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="contact-add-item">
                                            <div class="contact-icon text-primary mb-4">
                                                <i class="fab fa-firefox-browser fa-2x"></i>
                                            </div>
                                            <div>
                                                <h4>Yoursite@ex.com</h4>
                                                <p class="mb-0">(+012) 3456 7890</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="bg-light p-5 rounded h-100 wow fadeInUp" data-wow-delay="0.2s">
                              <h4 class="text-primary">Send Your Message</h4>
                              <p class="mb-4">The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done. <a class="text-primary fw-bold" href="https://htmlcodex.com/contact-form">Download Now</a>.</p>

                              <% if flash[:notice] %>
                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                  <%= flash[:notice] %>
                                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                              <% elsif flash[:alert] %>
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                  <%= flash[:alert] %>
                                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                              <% end %>

                              <%= form_with model: @contact, url: contact_index_path, local: true do |form| %>
                                  <div class="row g-4">
                                      <div class="col-lg-12 col-xl-6">
                                      <div>
                                          <label for="name">Your Name</label>
                                          <%= form.text_field :name, class: "form-control border-0", required: true %>
                                            <% if @contact.errors[:name].any? %>
                                            <div class="text-danger">
                                              <%= @contact.errors.full_messages_for(:name).join(", ") %>
                                            </div>
                                          <% end %>
                                      </div>
                                      </div>
                                      <div class="col-lg-12 col-xl-6">
                                      <div>
                                          <label for="email">Your Email</label>
                                          <%= form.email_field :email, class: "form-control border-0", required: true  %>
                                          <% if @contact.errors[:email].any? %>
                                            <div class="text-danger">
                                              <%= @contact.errors.full_messages_for(:email).join(", ") %>
                                            </div>
                                          <% end %>
                                      </div>
                                      </div>
                                      <div class="col-lg-12 col-xl-6">
                                      <div>
                                          <label for="phone">Your Phone</label>
                                          <%= form.telephone_field :phone, class: "form-control border-0", required: true %>
                                          <% if @contact.errors[:phone].any? %>
                                            <div class="text-danger">
                                              <%= @contact.errors.full_messages_for(:phone).join(", ") %>
                                            </div>
                                          <% end %>
                                      </div>
                                      </div>
                                      <div class="col-lg-12 col-xl-6">
                                      <div>
                                          <label for="project">Your Project</label>
                                          <%= form.text_field :project, class: "form-control border-0"%>
                                          <% if @contact.errors[:project].any? %>
                                            <div class="text-danger">
                                              <%= @contact.errors.full_messages_for(:project).join(", ") %>
                                            </div>
                                          <% end %>
                                      </div>
                                      </div>
                                      <div class="col-12">
                                      <div>
                                          <label for="subject">Subject</label>
                                          <%= form.text_field :subject, class: "form-control border-0", required: true %>
                                          <% if @contact.errors[:subject].any? %>
                                            <div class="text-danger">
                                              <%= @contact.errors.full_messages_for(:subject).join(", ") %>
                                            </div>
                                          <% end %>
                                      </div>
                                      </div>
                                      <div class="col-12">
                                      <div>
                                          <label for="message">Message</label>
                                          <%= form.text_area :message, class: "form-control border-0", style: "height: 160px", required: true %>
                                          <% if @contact.errors[:message].any? %>
                                            <div class="text-danger">
                                              <%= @contact.errors.full_messages_for(:message).join(", ") %>
                                            </div>
                                          <% end %>
                                      </div>
                                      </div>
                                      <div class="col-12">
                                          <%= form.submit "Send Message", class: "btn btn-primary w-100 py-3" %>
                                      </div>
                                  </div>
                              <% end %>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 wow fadeInRight" data-wow-delay="0.2s">
                        <div class="rounded h-100">
                            <iframe class="rounded h-100 w-100" 
                            style="height: 400px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387191.33750346623!2d-73.97968099999999!3d40.6974881!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sbd!4v1694259649153!5m2!1sen!2sbd" 
                            loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Contact End -->
    </body>
</html>

app/views/session/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Session</title>
</head>
<style>
@import url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Montserrat', sans-serif;
  backdrop-filter: blur(5px);
}

:root {
  --black-color: #fff;
}

body {
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  background: url(<%= asset_path('carousel-1.jpg') %>) no-repeat;
  background-size: cover;
  background-position: center;
}

.header {
  width: 100%;
  height: 6%;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 30px;
  background-color: rgba(0, 0, 0, 0.6); 
  position: absolute; 
  top: 0;
  left: 0;
  z-index: 1000; 
  border-bottom: 2px ridge rgba(255, 255, 255, 0.5);
  backdrop-filter: blur(2px);
}

.back-button {
  display: flex;
  align-items: center;
  text-decoration: none;
  color: #fff;
  font-size: 1em;
  font-weight: bold;
}

.back-button ion-icon {
  font-size: 1.5em;
  margin-right: 8px;
}

.back-button:hover {
  text-decoration: underline;
}

<%# .logo {
  display: flex;
  align-items: center;
}

.logo-image {
  height: 30px;
  margin-right: 10px;
} %>

.website-name {
  font-size: 1.2em;
  color: #fff;
  font-weight: bold;
}

.wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  width: 100%;
}

.login-box {
  position: relative;
  width: 400px;
  height: 350px;
  background: transparent;
  border-radius: 15px;
  border: 2px solid rgba(19, 255, 145, 0.8);
  display: flex;
  justify-content: center;
  align-items: center;
  backdrop-filter: blur(2px);
}

h2 {
  font-size: 2em;
  color: var(--black-color);
  text-align: center;
}

.input-box {
  position: relative;
  width: 310px;
  margin: 30px 0;
  border-bottom: 1px solid var(--black-color);
}

.input-box label {
  position: absolute;
  top: 50%;
  left: 5px;
  transform: translateY(-50%);
  font-size: 1em;
  color: var(--black-color);
  pointer-events: none;
  transition: .5s;
}

.input-box input:focus ~ label,
.input-box input:valid ~ label {
  top: -5px;
}

.input-box input {
  width: 100%;
  height: 50px;
  background: transparent;
  border: none;
  outline: none;
  font-size: 1em;
  color: var(--black-color);
  padding: 0 35px 0 5px;
}

.input-box .icon {
  position: absolute;
  right: 8px;
  top: 50%;
  color: var(--black-color);
  transform: translateY(-50%);
}

button {
  width: 100%;
  height: 40px;
  background-color: rgba(19, 255, 145, 0.8);
  border: 1px solid #fff;
  border-radius: 40px;
  cursor: pointer;
  font-size: 1em;
  color: #fff;
  font-weight: 500;
  transition: background-color 0.3s ease, color 0.3s ease;
}

button:hover {
  background-color: black;
  color: white;
}
</style>
<body>
  <div class="header">
    <a href="/home" class="back-button">
      <ion-icon name="arrow-back-circle"></ion-icon>
      Back
    </a>
    <%# <div class="logo">
      <img src="" alt="Website Logo" class="logo-image">
      <span class="website-name">Your Website</span>
    </div> %>
  </div>
  <div class="wrapper">
    <div class="login-box">
      <form action="/verify-otp">
        <h2>Login</h2>
        <div class="input-box">
          <span class="icon">
            <ion-icon name="phone"></ion-icon>
          </span>
          <input type="tel" value='+91-' required>
          <label>Mobile Number</label>
        </div>
        <button type="submit">Send OTP</button>
      </form>
    </div>
  </div>
</body>
</html>

app/views/session/verify_otp.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Session</title>
</head>
<style>
@import url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Montserrat', sans-serif;
  backdrop-filter: blur(5px);
}

:root {
  --black-color: #fff;
}

body {
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  background: url(<%= asset_path('carousel-1.jpg') %>) no-repeat;
  background-size: cover;
  background-position: center;
}

.header {
  width: 100%;
  height: 6%;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 30px;
  background-color: rgba(0, 0, 0, 0.6); 
  position: absolute; 
  top: 0;
  left: 0;
  z-index: 1000; 
  border-bottom: 2px ridge rgba(255, 255, 255, 0.5);
  backdrop-filter: blur(2px);
}

.back-button {
  display: flex;
  align-items: center;
  text-decoration: none;
  color: #fff;
  font-size: 1em;
  font-weight: bold;
}

.back-button ion-icon {
  font-size: 1.5em;
  margin-right: 8px;
}

.back-button:hover {
  text-decoration: underline;
}

<%# .logo {
  display: flex;
  align-items: center;
}

.logo-image {
  height: 30px;
  margin-right: 10px;
} %>

.website-name {
  font-size: 1.2em;
  color: #fff;
  font-weight: bold;
}

.wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  width: 100%;
}

.login-box {
  position: relative;
  width: 400px;
  height: 350px;
  background: transparent;
  border-radius: 15px;
  border: 2px solid rgba(19, 255, 145, 0.8);
  display: flex;
  justify-content: center;
  align-items: center;
  backdrop-filter: blur(2px);
}

h2 {
  font-size: 2em;
  color: var(--black-color);
  text-align: center;
}

.input-box {
  position: relative;
  width: 310px;
  margin: 30px 0;
  border-bottom: 1px solid var(--black-color);
}

.input-box label {
  position: absolute;
  top: 50%;
  left: 5px;
  transform: translateY(-50%);
  font-size: 1em;
  color: var(--black-color);
  pointer-events: none;
  transition: .5s;
}

.input-box input:focus ~ label,
.input-box input:valid ~ label {
  top: -5px;
}

.input-box input {
  width: 100%;
  height: 50px;
  background: transparent;
  border: none;
  outline: none;
  font-size: 1em;
  color: var(--black-color);
  padding: 0 35px 0 5px;
}

.input-box .icon {
  position: absolute;
  right: 8px;
  top: 50%;
  color: var(--black-color);
  transform: translateY(-50%);
}

button {
  width: 100%;
  height: 40px;
  background-color: rgba(19, 255, 145, 0.8);
  border: 1px solid #fff;
  border-radius: 40px;
  cursor: pointer;
  font-size: 1em;
  color: #fff;
  font-weight: 500;
  transition: background-color 0.3s ease, color 0.3s ease;
}

button:hover {
  background-color: black;
  color: white;
}
</style>
<body>
  <div class="header">
    <a href="/session" class="back-button">
      <ion-icon name="arrow-back-circle"></ion-icon>
      Back
    </a>
  </div>
  <div class="wrapper">
    <div class="login-box">
      <form action="/home">
        <h2>Verify</h2>

        <div class="input-box">
          <span class="icon">
            <ion-icon name="otp"></ion-icon>
          </span>
          <input type="otp" required>
          <label>Enter OTP</label>
        </div>

        <button type="submit">Verify OTP</button>
      </form>
    </div>
  </div>
</body>
</html>